### ISSUE TITLE
Unable to compile step 7 on Ubuntu 19.10 machine

### ISSUE THREAD

**Issue by mk8** [hybridgroup/gdg-2019#6] opened 2019-12-01 10:56 UTC
When I try to compile step 7 on my Ubuntu 19.10 machine I got the follow error:

tinygo: /home/circleci/project/llvm-project/llvm/include/llvm/Support/Casting.h:264: typename cast_retty<X, Y *>::ret_type llvm::cast(Y *) [X = llvm::ConstantExpr, Y = llvm::Value]: Assertion `isa<X>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
SIGABRT: abort
PC=0x7f41946bb3eb m=7 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7f41946bb3eb
stack: frame={sp:0x7f418b7fdb00, fp:0x0} stack=[0x7f418affe248,0x7f418b7fde48)
00007f418b7fda00:  0000000000000000  2e6f6861702f6573 
00007f418b7fda10:  6c6f672e7474716d  f5d76b8345e4c400 
00007f418b7fda20:  0000000000000000  0000000000000115 
00007f418b7fda30:  00007f417810baa0  0000000000000110 
00007f418b7fda40:  00007f4178000020  00007f417810bbe0 
00007f418b7fda50:  0000000000000004  00007f41947110f2 
00007f418b7fda60:  0000000000000001  0000003100000007 
00007f418b7fda70:  0000000000000000  00007f4178000020 
00007f418b7fda80:  00007f417810bab0  0000000000000106 
00007f418b7fda90:  0000000000000106  00007f417810baa0 
00007f418b7fdaa0:  0000000000000140  00007f4194713306 
00007f418b7fdab0:  343632418b7fdb10  f5d76b8345e4c400 
00007f418b7fdac0:  00007f417810ba40  00007f418b7fdd60 
00007f418b7fdad0:  0000000000000105  0000000000000105 
00007f418b7fdae0:  0000000000000106  00007f417810bab0 
00007f418b7fdaf0:  00007f418b7fdb10  00007f4194703c99 
00007f418b7fdb00: <0000000000000000  00007f4194712880 
00007f418b7fdb10:  00007f41fbad8000  00007f417810bab0 
00007f418b7fdb20:  00007f417810bb15  00007f417810bab0 
00007f418b7fdb30:  00007f417810bab0  00007f417810bbb5 
00007f418b7fdb40:  00007f417810bbdc  00007f417810bab0 
00007f418b7fdb50:  00007f417810bbdc  0000000000000000 
00007f418b7fdb60:  0000000000000000  0000000000000000 
00007f418b7fdb70:  0000000000000000  0000000000000000 
00007f418b7fdb80:  fffffffe7fffffff  ffffffffffffffff 
00007f418b7fdb90:  ffffffffffffffff  ffffffffffffffff 
00007f418b7fdba0:  ffffffffffffffff  ffffffffffffffff 
00007f418b7fdbb0:  ffffffffffffffff  ffffffffffffffff 
00007f418b7fdbc0:  ffffffffffffffff  ffffffffffffffff 
00007f418b7fdbd0:  ffffffffffffffff  ffffffffffffffff 
00007f418b7fdbe0:  ffffffffffffffff  ffffffffffffffff 
00007f418b7fdbf0:  ffffffffffffffff  ffffffffffffffff 
runtime: unknown pc 0x7f41946bb3eb
stack: frame={sp:0x7f418b7fdb00, fp:0x0} stack=[0x7f418affe248,0x7f418b7fde48)

**Comment by IvanMazzoli** [comment] 2019-12-01 11:00
I've got a similar error with Windows 10:

Exception 0xc0000005 0x0 0xfffffff8111078ec 0x2c1da89
PC=0x2c1da89

runtime: unknown pc 0x2c1da89
stack: frame={sp:0x85efde8, fp:0x0} stack=[0x0,0x85efe80)
00000000085efce8:  0000000002c29599  000000000041ecf6 <runtime.(*treapNode).updateInvariants+86>
00000000085efcf8:  0000000008c09230  0000000000000001
00000000085efd08:  000000016194083d  000000000000000c
00000000085efd18:  0000000000000001  0000000000000004
00000000085efd28:  0000000006d15810  000000000d84e270
00000000085efd38:  ffffffffffffffff  0000000000000003
00000000085efd48:  0000000000000002  0000000000000100
00000000085efd58:  000000000254472b  0000000000427e79 <runtime.(*mheap).allocSpanLocked+425>
00000000085efd68:  00000000048e3b20  00000000085efdd0
00000000085efd78:  0000000002cc0988  0000000009afeed0
00000000085efd88:  0000000009afeed0  0000000000000200
00000000085efd98:  0000000009afeed0  000000c005f83bc0
00000000085efda8:  000000c005f83b28  000000c0000d0180
00000000085efdb8:  000000c005f86000  000000c005f83ae8
00000000085efdc8:  ffffffffffffffff  0000000000000003
00000000085efdd8:  0000000000000002  0000000000000100
00000000085efde8: <00000000007bf72a  0000000009afeed0
00000000085efdf8:  00000000048fbae8  0000000009afeed0
00000000085efe08:  000000c0000d0180  000000c005f83b30
00000000085efe18:  000000c0000d0180  000000c005f83b30
00000000085efe28:  000000000045b5a3 <runtime.asmcgocall+115>  0000000000457af3 <runtime.(*mheap).alloc.func1+83>
00000000085efe38:  00000000048e3b20  0000000000000001
00000000085efe48:  0000000000450007 <runtime.gentraceback+2263>  0000000009afeed0
00000000085efe58:  0000000000002540  000000c000038000
00000000085efe68:  0000000000459d5b <runtime.systemstack+107>  0000000000435f60 <runtime.mstart+0>
00000000085efe78:  0000000006d16bd0
runtime: unknown pc 0x2c1da89
stack: frame={sp:0x85efde8, fp:0x0} stack=[0x0,0x85efe80)
00000000085efce8:  0000000002c29599  000000000041ecf6 <runtime.(*treapNode).updateInvariants+86>
00000000085efcf8:  0000000008c09230  0000000000000001
00000000085efd08:  000000016194083d  000000000000000c
00000000085efd18:  0000000000000001  0000000000000004
00000000085efd28:  0000000006d15810  000000000d84e270
00000000085efd38:  ffffffffffffffff  0000000000000003
00000000085efd48:  0000000000000002  0000000000000100
00000000085efd58:  000000000254472b  0000000000427e79 <runtime.(*mheap).allocSpanLocked+425>
00000000085efd68:  00000000048e3b20  00000000085efdd0
00000000085efd78:  0000000002cc0988  0000000009afeed0
00000000085efd88:  0000000009afeed0  0000000000000200
00000000085efd98:  0000000009afeed0  000000c005f83bc0
00000000085efda8:  000000c005f83b28  000000c0000d0180
00000000085efdb8:  000000c005f86000  000000c005f83ae8
00000000085efdc8:  ffffffffffffffff  0000000000000003
00000000085efdd8:  0000000000000002  0000000000000100
00000000085efde8: <00000000007bf72a  0000000009afeed0
00000000085efdf8:  00000000048fbae8  0000000009afeed0
00000000085efe08:  000000c0000d0180  000000c005f83b30
00000000085efe18:  000000c0000d0180  000000c005f83b30
00000000085efe28:  000000000045b5a3 <runtime.asmcgocall+115>  0000000000457af3 <runtime.(*mheap).alloc.func1+83>
00000000085efe38:  00000000048e3b20  0000000000000001
00000000085efe48:  0000000000450007 <runtime.gentraceback+2263>  0000000009afeed0
00000000085efe58:  0000000000002540  000000c000038000
00000000085efe68:  0000000000459d5b <runtime.systemstack+107>  0000000000435f60 <runtime.mstart+0>
00000000085efe78:  0000000006d16bd0

goroutine 1 [syscall]:
tinygo.org/x/go-llvm._Cfunc_LLVMGetConstOpcode(0x12f77d48, 0x0)
        _cgo_gotypes.go:5399 +0x50
tinygo.org/x/go-llvm.Value.Opcode.func1(0x12f77d48, 0x8)
        C:/Users/VssAdministrator/go/pkg/mod/tinygo.org/x/go-llvm@v0.0.0-20191124211856-b2db3df3f257/ir.go:873 +0x5d
tinygo.org/x/go-llvm.Value.Opcode(0x12f77d48, 0x6d15810)
        C:/Users/VssAdministrator/go/pkg/mod/tinygo.org/x/go-llvm@v0.0.0-20191124211856-b2db3df3f257/ir.go:873 +0x32
github.com/tinygo-org/tinygo/interp.(*MapValue).PutBinary(0xc005a871f0, 0xc0067f1830, 0xc0067f1870)
        D:/a/1/s/interp/values.go:370 +0xcc
github.com/tinygo-org/tinygo/interp.(*frame).evalBasicBlock(0xc005f85288, 0xdf37f80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        D:/a/1/s/interp/frame.go:299 +0x9598
github.com/tinygo-org/tinygo/interp.(*evalPackage).function(0xc005f854b0, 0x6d557b8, 0xc005f854c8, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        D:/a/1/s/interp/interp.go:113 +0x242
github.com/tinygo-org/tinygo/interp.Run(0x6d08870, 0xc000000000, 0x0, 0x0)
        D:/a/1/s/interp/interp.go:85 +0x808
github.com/tinygo-org/tinygo/builder.Build(0xc000018128, 0x7, 0xc0000180e0, 0x9, 0xc0001b2ed0, 0xc005f85c88, 0x0, 0x0)
        D:/a/1/s/builder/build.go:49 +0x1fc
main.Build(0xc000018128, 0x7, 0xc0000180e0, 0x9, 0xc000186000, 0x0, 0x1c)
        D:/a/1/s/main.go:84 +0xcc
main.main()
        D:/a/1/s/main.go:601 +0x193f

goroutine 6 [syscall]:
os/signal.signal_recv(0x0)
        C:/Go1.13/src/runtime/sigqueue.go:147 +0xa3
os/signal.loop()
        C:/Go1.13/src/os/signal/signal_unix.go:23 +0x29
created by os/signal.init.0
        C:/Go1.13/src/os/signal/signal_unix.go:29 +0x48
rax     0xfe6c2744
rbx     0xc005f83b30
rcx     0x0
rdi     0xc005f86000
rsi     0xc0000d0180
rbp     0xc005f83af0
rsp     0x85efde8
r8      0xffffffff019758bc
r9      0x0
r10     0x0
r11     0x61
r12     0xffffffffffffffff
r13     0x3
r14     0x2
r15     0x100
rip     0x2c1da89
rflags  0x10293
cs      0x33
fs      0x53
gs      0x2b

Also I can't build anything else after this error:
PS C:\Users\Ivan Mazzoli\Desktop\gdg-2019\sensor\arduino\Step6> tinygo flash -target arduino-nano33 main.go
error: failed to reset port C:\Users\IVANMA~1\AppData\Local\Temp\tinygo986297415\main.bin: opening port: Impossibile trovare il percorso specificato.

**Comment by garnaizd** [comment] 2019-12-01 11:16
It's working for my computer.
- Mac version: 10.14.6 (18G103) (macOS Mojave)
- go version: go1.13.3 darwin/amd64

Thanks

**Comment by titimoby** [comment] 2019-12-02 09:39
Exact same issue during GDG europe summit workshop with my Ubuntu 19.10

**Comment by titimoby** [comment] 2019-12-02 12:50
As far as I understand, it comes from "tinygo.org/x/drivers/espat/mqtt"

**Comment by aykevl** [comment] 2019-12-02 14:31
It's hard to say what the problem is for @mk8, because the stack trace is missing.
However, I can say that the problem reported by @IvanMazzoli should be fixed with this PR: https://github.com/tinygo-org/tinygo/pull/755.

**Comment by aykevl** [comment] 2019-12-03 15:55
@IvanMazzoli

> Also I can't build anything else after this error:
> PS C:\Users\Ivan Mazzoli\Desktop\gdg-2019\sensor\arduino\Step6> tinygo flash -target arduino-nano33 main.go
> error: failed to reset port C:\Users\IVANMA~1\AppData\Local\Temp\tinygo986297415\main.bin: opening port: Impossibile trovare il percorso specificato.

We never really tested flashing in Windows and it probably doesn't work yet - simply because none of the core developers use Windows. There is a theoretical chance it will work with a `-port=COM1` or similar, so you could try that.

**Comment by deadprogram** [comment] 2019-12-03 16:51
`tinygo flash` does not yet work in WIndows. You must first `tinygo build` and then flash using `bossac` manually.

**Comment by IvanMazzoli** [comment] 2019-12-03 18:52
> 
> 
> `tinygo flash` does not yet work in WIndows. You must first `tinygo build` and then flash using `bossac` manually.

Yeah, that's basically what I did during the workshop. I'll try again with the fix in tinygo-org/tinygo#755.

**Comment by aykevl** [comment] 2019-12-03 19:00
> I'll try again with the fix in tinygo-org/tinygo#755.

That PR is unrelated to Windows support, so unfortunately won't help. I'm afraid flashing manually is the way to go at the moment (unless you want to help improve Windows support, that help would be very welcome!).

**Comment by mk8** [comment] 2019-12-05 08:32
I can try the patch but I'm not able to install TINYGO from source.
Seems that the command 

`go get -d -u github.com/tinygo-org/tinygo
`

described in tinygo website download a lot of things but not the tinygo source code

**Comment by bgould** [comment] 2019-12-05 13:08
@mk8 You might need to temporarily set GO111MODULE=off when running the `go get` command to cause the tinygo source to be downloaded to your GOPATH, otherwise the go tool will probably try to download it as a module.  Alternatively you might try cloning with git instead; there will be manual steps after getting the source anyhow (`make gen-device`) so `go get` won't completely get the job done regardless.

**Comment by aykevl** [comment] 2019-12-05 23:11
> Seems that the command
> 
>     go get -d -u github.com/tinygo-org/tinygo
> 
> described in tinygo website download a lot of things but not the tinygo source code

What kind of things?
Note that there are a few submodules that are necessary for building for bare metal devices.

> You might need to temporarily set GO111MODULE=off when running the go get command to cause the tinygo source to be downloaded to your GOPATH, otherwise the go tool will probably try to download it as a module.

Maybe there is a problem when running `go get` inside another Go module? Other than that, I can't think of a reason why `go get` would fail.

**Comment by bgould** [comment] 2019-12-06 04:49
> Maybe there is a problem when running `go get` inside another Go module? Other than that, I can't think of a reason why `go get` would fail.

If I'm not mistaken, this is the case.  I believe the behavior of 'go get' when run inside of a module with GO111MODULE=on (or GO111MODULE=auto and not on GOPATH) is to add the requested module as a dependency to the go.mod file.

One way to tell which behavior is used is to use `go help get`; when it modules mode the help text starts out like this:

```
go help get
usage: go get [-d] [-m] [-u] [-v] [-insecure] [build flags] [packages]

Get resolves and adds dependencies to the current development module
and then builds and installs them.
```

when in "old" GOPATH mode the help text starts like this:

```
usage: go get [-d] [-f] [-t] [-u] [-v] [-fix] [-insecure] [build flags] [packages]

Get downloads the packages named by the import paths, along with their
dependencies. It then installs the named packages, like 'go install'.
```

**Comment by aykevl** [comment] 2019-12-19 12:50
Did some more digging. I found that the panic occurs due to a map update in the github.com/eclipse/paho.mqtt.golang/packets package, in a global initializer on line 23 column 35 (but not the file, because of some reasons). The only file where this can happen is packets.go, with the following code:

```go
var PacketNames = map[uint8]string{
	1:  "CONNECT",
	2:  "CONNACK",
	3:  "PUBLISH",
	4:  "PUBACK",
	5:  "PUBREC",
	6:  "PUBREL",
	7:  "PUBCOMP",
	8:  "SUBSCRIBE",
	9:  "SUBACK",
	10: "UNSUBSCRIBE",
	11: "UNSUBACK",
	12: "PINGREQ",
	13: "PINGRESP",
	14: "DISCONNECT",
}
```

And indeed, I could reproduce it with just that.

**Comment by aykevl** [comment] 2019-12-19 13:25
This should fix the root cause: https://github.com/tinygo-org/tinygo/pull/787

**Comment by deadprogram** [comment] 2019-12-20 00:49
This was merged into `dev` branch of TinyGo, so now closing. Thank you everyone!

**Closed as completed by deadprogram** 2019-12-20 00:49 UTC
